### ISSUE TITLE
API_key? && Big thank you

### ISSUE THREAD

**Issue by RevRebel** [AutoIDM/tap-clickup#108]
First, thank you for making this. I've been searching for a ClickUp connector forever, you are my hero this week!

Seeing this for the first time with outside eyes, it's not clear where you store or place the API_key and I haven't been able to figure it out. When passing the --config or -config flags, it doesn't seem to work either. Any insight would be awesome.

<img width="666" alt="Screen Shot 2022-01-26 at 7 59 46 AM" src="https://user-images.githubusercontent.com/93675875/151199341-2112a110-3597-48b2-aada-33d00f396b13.png">

<img width="824" alt="Screen Shot 2022-01-26 at 7 56 56 AM" src="https://user-images.githubusercontent.com/93675875/151199348-a46f7991-f6d3-4448-9fd8-1402096101fd.png">

**Comment by visch** [comment]
Thanks for the thank you!

So this "tap" is following a spec called Singer (I should probably call this out). https://github.com/singer-io/getting-started is official, but I think https://hub.meltano.com/singer/spec is easier to skim/read. 

Taps (like this one tap-clickup) expect a config to be passed into them, ie `tap-clickup --config=config.json` This config file needs to have the environment variable.

To skip a lot of this boiler plate setup (if you're just looking to get data to work with), use the steps at the bottom of the readme for Meltano https://github.com/AutoIDM/tap-clickup#testing-with-meltano .  Install meltano (then you can add the api_key to https://github.com/AutoIDM/tap-clickup/blob/main/meltano.yml#L6

Something like

```
config:
  api_key: abc
```

Would work.

**Comment by visch** [comment]
If you use Meltano then in airflow you can use (a bash operator I think they call it) a command like `meltano elt tap-clickup target-csv` or something like that

**Comment by visch** [comment]
Just realized you were running pytest, yes to get that working set https://github.com/AutoIDM/tap-clickup/blob/main/tap_clickup/tests/test_core.py#L12 the env variable there (no config needed, you can setup a .env if you want, probably should support both use cases)

**Comment by RevRebel** [comment]
Thanks, everyone, that was really helpful.  just getting familiar with Singer and noticed the same with some other taps as well.

**Comment by visch** [comment]
Everything working? Good to close this?
