### ISSUE TITLE
Add support for tasks.date_done

### ISSUE THREAD

**Issue by JohannesRudolph** [AutoIDM/tap-clickup#137]
ClickUp tasks api offers date_done field in addition to date_closed, just needs to be added to the schema

https://github.com/meshcloud/tap-clickup-forked/commit/b537381a5ae649365fb62d24b714cc9c4904b9c4

Works great in our pipelines.

**Comment by visch** [comment]
@JohannesRudolph  looks easier enough if you could throw in a PR in the future it would make my life a lot easier here. I'll try to put it in right now!

**Comment by JohannesRudolph** [comment]
@visch yes - sorry for making it as troublesome. I've asked my team to work on upstreaming some of the improvements we hacked into our fork (we were in a bit of a hurry...) with proper PRs. Will take a bit of time.
