### ISSUE TITLE
Extracting Tasks: KeyError: 'date_updated'

### ISSUE THREAD

**Issue by leo-neves** [AutoIDM/tap-clickup#140]
I am having some problems to get tasks, I'm getting the following KeyError, so it stops the extraction. Is that any known issue?

` [info     ] KeyError: 'date_updated'       cmd_type=elb consumer=False name=tap-clickup producer=True stdio=stderr string_id=tap-clickup`
`[error    ] Extractor failed`
`[error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Extractor failed') exit_codes={<PluginType.EXTRACTORS: 'extractors'>: 1} set_number=0 success=False`

Any idea of what could be happening? 

Thanks in advance

**Comment by sebastianswms** [comment]
This is not a known issue, and I can't immediately replicate the behavior you're experiencing. Could you please provide more information about the specific configuration you're using and the data you're attempting to extract?

**Comment by leo-neves** [comment]
Thank you for answering, @sebastianswms, I'm extracting the data with the tap-clickup on meltano. I am using the latest version of python, meltano and of the dependencies. I need to get most of the attributes from tasks, specially ids, statuses, time spent and time estimated. If I get data from spaces or folders, it works fine, the only issue I faced was with tasks.

**Comment by sebastianswms** [comment]
I'm still having trouble replicating your problem. Could you provide more detailed steps to recreate your problem?

**Comment by visch** [comment]
Oh I see @leo-neves  , add to your select statement `task. date_updated` we require it due to incremental streams right now. Ideally we'd auto select it for you! Does that work @leo-neves 



I think a later version of the meltano sdk fixes this but if we upgrade we should be careful @sebastianswms  due to https://github.com/AutoIDM/tap-clickup/blob/main/tap_clickup/client.py#L137 but upgrading this would eliminate this issue

**Comment by visch** [comment]
@sebastianswms  Looks like you already bumped that with your last PR. We also need to cut a release to `pypi`  and then I think @leo-neves  could just update and we'd be good

**Comment by leo-neves** [comment]
Thanks heaps @visch, that worked like a charm. Cheers

**Comment by visch** [comment]
@leo-neves  I don't understand what you're asking, sorry :(
