### ISSUE TITLE
Invalid Due_date schema type for List Schema

### ISSUE THREAD

**Issue by LucasZielke** [AutoIDM/tap-clickup#50]
The ClickUp Api dictates that the values for the due_date are defined by `$.due_date` which makes it appear that they are assigned in relation to `$.due_date_time = bool` . Where if `$.due_date_time = true` than `$.due_date` is a datetime string thats in epoch whereas the singer specifications are based on "Json-schema" which are expecting it to be in Unix timestamp ([RFC3339](https://datatracker.ietf.org/doc/html/rfc3339))

**Comment by visch** [comment]
I've found a number of inconsistencies with their documentation (which shows one example of the data) and production data. I can take a look at this one!

To generate the json schema's I tried using produciton data (or as close as I could to production data)

Is this leading to any errors on your end that you could post?

**Comment by visch** [comment]
Thank you so much for that @LucasZielke  , appreciate it!
