### ISSUE TITLE
List and Folderless_list mismatched attributes

### ISSUE THREAD

**Issue by LucasZielke** [AutoIDM/tap-clickup#51]
It seems like in the differences in the streams for List and Folderless_List, two attributes are picked up making it, `CONTENT` and `STATUS`, I forgot which one got the two additional attributes but I will look that up shortly

**Comment by visch** [comment]
Thank you for the issue! 

Is there an error in the logs or something that's failing directly I could look at? It would help a bunch!

Both of the streams are currently using the same schema file
https://github.com/AutoIDM/tap-clickup/blob/main/tap_clickup/streams.py#L75
https://github.com/AutoIDM/tap-clickup/blob/main/tap_clickup/streams.py#L93

**Comment by visch** [comment]
Going to close this @LucasZielke , if you have an example we can reopen!

**Comment by LucasZielke** [comment]
No problem, seems it had to do with target-postgres and not the tap-clickup anyways
