### ISSUE TITLE
Add support for time entries

### ISSUE THREAD

**Issue by JohannesRudolph** [AutoIDM/tap-clickup#98]
Thanks for building this tap! Getting time entries out of ClickUp is really useful for data warehousing, e.g. building project reports. We've done so using google apps scripts for a while, but I want to migrate this to a more mature stack and looking into meltano/singer. 

Here's what we're currently doing: 

```javascript
  // we need to manually fetch assignees first... 
  const team = getClickUp_Team_();
  const userIds = team.teams[0].members.map(x => x.user.id).join(",");

  // The ClickUp TimeEntry API is... crap. By putting in start_date=0 we tell it to give us all data from the beginning of time without paging
  const url = "https://api.clickup.com/api/v2/team/2488205/time_entries?start_date=0&assignee=" + userIds;
``` 

I understand that this could be modeled as a dependent stream in a way? (time_entries stream depends on team?)

**Comment by visch** [comment]
Yes a TimeEntry stream, with a parent of Team would (seemingly) work well here. How long does it take (roughly) for all of your time entries to come over? We could just pull them all, or implement an incremental model to save the state (so we don't pull them all every time, if timing is an issue)

**Comment by JohannesRudolph** [comment]
We're currently not loading incremental, takes about 15s for 5000 entries which I think is fine for now. Incremental mode thus wouldn't have to be on the list I'd say. 

Incremental might have the problem that in a certain "active" time window of a couple weeks records might get changed around (clickup allows deleting/modifying entries and that's also often used in real world settings ;-) ).
